### ISSUE TITLE
Is there any new version of MapGuideDotNetApi ?

### ISSUE THREAD

**Issue by diordonez** [jumpinjackie/mapguide-api-bindings#37]
What Target CORE Framework will be compatible with MapGuideDotNetApi.3.1.1.9378-pre74.nupkg ?

I'm getting this error 

dotnet add GoeMapping.CORE package MapGuideDotNetApi --version 3.1.1.9378-pre74

error: Package 'MapGuideDotNetApi' is incompatible with 'all' frameworks in project 'D:\Development\GOEMapping\Development\GoeMapping.CORE\GoeMapping.CORE\GoeMapping.CORE.csproj'.

Thanks for your help

**Comment by jumpinjackie** [comment]
Please note that development work on this repo has been suspended and is continuing on the [vanilla_swig](https://trac.osgeo.org/mapguide/browser/sandbox/jng/vanilla_swig) branch of MapGuide. There will be no more updates to the repo.

To answer your question at hand. `MapGuideDotNetApi.3.1.1.9378-pre74.nupkg` is a `netstandard2.0` package. So any version of .net in [this table](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) should be able to consume this package. Also note that the multi-platform-ness of this package is incomplete at the time that package was created, so the package will not work on frameworks like Xamarin/Unity/etc and platforms like MacOS despite being `netstandard2.0` compatible in the referenced table.

**Comment by diordonez** [comment]
Thank you.
So according to your response I'd rather abort my project with .NET Core, and stick with the .NET one, at least I can easily find the libraries in NuGET.


Cheers

**Comment by jumpinjackie** [comment]
For now, yes.
